# Deployment do PostgreSQL
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgre
          image: postgres:13.1
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: Passw0rd2024!
            - name: POSTGRES_USER
              value: reviewdefilmes
            - name: POSTGRES_DB
              value: reviewdefilmes
---
# Service do PostgreSQL
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
  type: ClusterIP
---
# Deployment da aplicação
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviewdefilmes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviewdefilmes
  template:
    metadata:
      labels:
        app: reviewdefilmes
    spec:
      containers:
        - name: reviewdefilmes
          image: mariannactx/review-filmes:v1
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_HTTP_PORTS
              value: '8080'
            - name: ConnectionStrings_DefaultConnection
              value: 'Host=postgres;Database=reviewdefilmes;Username=reviewdefilmes;Password=Passw0rd2024!'
---
# Service da aplicação
apiVersion: v1
kind: Service
metadata:
  name: reviewdefilmes
spec:
  selector:
    app: reviewdefilmes
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
